### ISSUE TITLE
Comment feature

### ISSUE THREAD

**Issue by bozzmob** [jamstack-cms/jamstack-cms#2]
Hi Nader,

I went over the README, as you've already mentioned, the comment feature will be the most important feature, as it would increase engagement. Just wanted your thoughts on - If there was some native way of building the comments feature?
Disqus is great for most of them, but, I want something that goes with the website.
I'd also checked out [staticman](https://github.com/eduardoboucas/staticman). 

What your view? What would be the approach you'd want to consider for jamstack-cms?

**Comment by itsJASPERr** [comment]
The conference in a box app From Nader has a comment feature. The app is built with amplify and react native And graphql, so it would only have to be adapted to gatsby and the according models. But essentially it could be copied, I'd say. No need to rely on third party services/apps in this case imo.
However, you just pointed me to exactly what I was looking for (staticman) for a project. Thanks! 🙏

**Comment by bozzmob** [comment]
@itsJASPERr Thank you for introducing me to the Conference App. I'll take a look at that.

Yes, staticman is a cool project :) Have fun exploring!
